// Stamp src/core/version.ts from package.json "version".
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8'));
const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit. Mirrors package.json "version".
/** The @energy8platform/shell package version, stamped into the game-info footer. */
export const PACKAGE_VERSION = '${pkg.version}';
`;
writeFileSync(join(here, '..', 'src', 'core', 'version.ts'), out);
console.log(`shell: wrote version.ts (${pkg.version})`);
