import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const VIRTUAL_ID = 'virtual:e8-project';
const RESOLVED_ID = '\0' + VIRTUAL_ID;

export interface ProjectPluginOptions {
  /** Project root holding `project.json`. Defaults to the Vite root at config time. */
  root?: string;
  /** Filename, if a project keeps several. Defaults to `project.json`. */
  projectFile?: string;
}

/**
 * Turn `project.json` into a module a bundler can see.
 *
 * The kernel reads plugin manifests as objects, but a browser bundle cannot read a file off disk.
 * So the project's plugin list becomes STATIC imports here — static because a bundler has to see
 * them to include the code. The emitted module exports `project` (verbatim) and `manifests`
 * (in the project's own key order, which is what makes the plan reproducible).
 *
 * Node-only. Never let this file into a browser bundle.
 */
export function projectPlugin(options: ProjectPluginOptions = {}) {
  let root = options.root ?? process.cwd();
  const file = options.projectFile ?? 'project.json';

  return {
    name: 'e8:project',

    configResolved(config: { root: string }): void {
      if (!options.root) root = config.root;
    },

    resolveId(id: string): string | null {
      return id === VIRTUAL_ID ? RESOLVED_ID : null;
    },

    async load(id: string): Promise<string | null> {
      if (id !== RESOLVED_ID) return null;

      const path = join(root, file);
      let raw: string;
      try {
        raw = readFileSync(path, 'utf8');
      } catch {
        throw new Error(`e8:project — could not read ${file} at ${path}`);
      }

      let project: { plugins?: Record<string, unknown> };
      try {
        project = JSON.parse(raw) as { plugins?: Record<string, unknown> };
      } catch (err) {
        throw new Error(
          `e8:project — ${file} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
        );
      }

      const ids = Object.keys(project.plugins ?? {});
      const imports = ids.map((specifier, i) => `import m${i} from '${specifier}';`).join('\n');
      const list = ids.map((_, i) => `m${i}`).join(', ');

      return [
        '// Generated by e8:project — do not edit.',
        imports,
        `export const project = ${JSON.stringify(project, null, 2)};`,
        `export const manifests = [${list}];`,
        '',
      ].join('\n');
    },
  };
}
