// AUTO-GENERATED by scripts/gen-version.mjs — do not edit. Mirrors package.json "version".
/** The @energy8platform/shell package version, stamped into the game-info footer. */
export const PACKAGE_VERSION = '0.11.4';
