#!/usr/bin/env node
// Regenerates src/shell/version.ts from package.json so the bundled shell can stamp the
// engine version into the game-info footer without importing package.json at runtime (no
// JSON-bundling plugin in the rollup pipeline). Wired as the `prebuild` npm script, so every
// `npm run build` (and `prepublishOnly`) refreshes it; committed like the generated fonts.ts.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(await readFile(resolve(here, '../package.json'), 'utf8'));
const out = resolve(here, '../src/shell/version.ts');

const body = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit. Mirrors package.json "version".
/** The @energy8platform/platform-core package version, stamped at build time. */
export const PACKAGE_VERSION = '${pkg.version}';
`;

await writeFile(out, body);
console.log(`wrote ${out} (PACKAGE_VERSION = ${pkg.version})`);
