// AUTO-GENERATED by scripts/gen-version.mjs — do not edit. Mirrors package.json "version".
/** The @energy8platform/platform-core package version, stamped at build time. */
export const PACKAGE_VERSION = '0.25.0';
